kind: pipeline
type: docker
name: default

steps:
  - name: yarn install
    image: node
    volumes:
      - name: cache
        path: /drone/src/node_modules
    commands:
      - yarn install --registry https://registry.npm.taobao.org/
  - name: yarn build
    image: node
    volumes:
      - name: cache
        path: /drone/src/node_modules
      - name: env
        path: /drone/src/.env
    environment:
      DOMAIN:
        from_secret: DOMAIN
      API_DOMAIN:
        from_secret: API_DOMAIN
      PROTOCOL:
        from_secret: PROTOCOL
      SKIP_PREFLIGHT_CHECK:
        from_secret: SKIP_PREFLIGHT_CHECK
      VITE_DOMAIN:
        from_secret: REACT_APP_DOMAIN
      VITE_URL:
        from_secret: REACT_APP_URL
      VITE_API_DOMAIN:
        from_secret: REACT_APP_API_DOMAIN
      VITE_API_URL:
        from_secret: REACT_APP_API_URL
      VITE_FUNDEBUG_API_KEY:
        from_secret: REACT_APP_FUNDEBUG_API_KEY
      VITE_CDN_URL:
        from_secret: REACT_APP_CDN_URL
      VITE_OSS_URL:
        from_secret: REACT_APP_OSS_URL
      VITE_ALGOLIA_APP_ID:
        from_secret: REACT_APP_ALGOLIA_APP_ID
      VITE_ALGOLIA_APP_KEY:
        from_secret: REACT_APP_ALGOLIA_APP_KEY
      VITE_NAME:
        from_secret: REACT_APP_NAME
      VITE_SENTRY_DSN:
        from_secret: REACT_APP_SENTRY_DSN
      VITE_PUSHER_APP_KEY:
        from_secret: REACT_APP_PUSHER_APP_KEY
      VITE_PUSHER_HOST:
        from_secret: REACT_APP_PUSHER_HOST
      VITE_PUSHER_PORT:
        from_secret: REACT_APP_PUSHER_PORT
      VITE_GITHUB_CLIENT_ID:
        from_secret: REACT_APP_GITHUB_CLIENT_ID
    commands:
      - yarn run build
  - name: rsync
    image: drillster/drone-rsync
    settings:
      user: root
      key:
        from_secret: ssh_key
      hosts:
        - 172.22.253.15
      # 来源项目目录
      source: ./dist/*
      delete: true
      # 目标服务器目录
      target: /var/www/antic/static
#      script:
#        - cd /var/www/antic
#        - ls

trigger:
  event:
    - push

volumes:
  - name: cache
    host:
      path: /tmp/cache
  - name: env
    host:
      path: /var/www/antic/.env

