kind: pipeline
type: docker
name: default

trigger:
  event:
    - push

volumes:
  - name: cache
    host:
      path: /tmp/drone/antic # need create the drone folder before git push.

steps:
  - name: yarn install
    image: node
    volumes:
      - name: cache # cache the node_modules folder to volume name:cache.
        path: /drone/src/node_modules
    commands:
      - yarn install --registry https://registry.npm.taobao.org/
  - name: yarn build
    image: node
    volumes:
      - name: cache
        path: /drone/src/node_modules
    environment:
      SKIP_PREFLIGHT_CHECK:
        from_secret: SKIP_PREFLIGHT_CHECK
      VITE_DOMAIN:
        from_secret: VITE_DOMAIN
      VITE_API_URL:
        from_secret: VITE_API_URL
      VITE_FUNDEBUG_API_KEY:
        from_secret: VITE_FUNDEBUG_API_KEY
      VITE_ALGOLIA_APP_ID:
        from_secret: VITE_ALGOLIA_APP_ID
      VITE_ALGOLIA_APP_KEY:
        from_secret: VITE_ALGOLIA_APP_KEY
      VITE_NAME:
        from_secret: VITE_NAME
      VITE_SENTRY_DSN:
        from_secret: VITE_SENTRY_DSN
      VITE_PUSHER_APP_KEY:
        from_secret: VITE_PUSHER_APP_KEY
      VITE_PUSHER_HOST:
        from_secret: VITE_PUSHER_HOST
      VITE_PUSHER_PORT:
        from_secret: VITE_PUSHER_PORT
      VITE_GITHUB_CLIENT_ID:
        from_secret: VITE_GITHUB_CLIENT_ID
    commands:
      - export NODE_OPTIONS=--max-old-space-size=8096 # no setting will cause the vite build error.
      - yarn build
  - name: rsync
    image: drillster/drone-rsync
    settings:
      user: ecs-user # 这个方式是否正确？
      key:
        from_secret: ssh_key
      hosts:
        - 172.16.65.147 # 这个方式是否正确？
      source: ./dist/*
      delete: true
      target: /var/www/antic/static

