version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    executor:
      name: node/default
      tag: '16.17.0'
    steps:
      - checkout
      - run: yarn
      - run:
          name: Danger
          command: yarn danger ci
