name: React
on: [push]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: build
    env:
      REACT_APP_NAME: ${{ secrets.APP_NAME }}
      REACT_APP_CDN_URL: ${{ secrets.APP_CDN_URL }}
      REACT_APP_DOMAIN: ${{ secrets.APP_DOMAIN }}
      REACT_APP_API_URL: ${{ secrets.APP_API_URL }}
      REACT_APP_SENTRY_DSN: ${{ secrets.APP_SENTRY_DSN }}
      REACT_APP_URL: ${{ secrets.APP_URL }}
    steps:
      - name: Checkout    
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: yarn
      - name: Build
        run: yarn build

      - name: Deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: '${{ secrets.USER }}'
          server: '${{ secrets.SERVER_IP }}'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: './build/*'
          remote_path: '/var/www/antic/static'
